#ifndef STATISTIQUE_GLOBAL_H
#define STATISTIQUE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STATISTIQUE_LIBRARY)
#  define STATISTIQUESHARED_EXPORT Q_DECL_EXPORT
#else
#  define STATISTIQUESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STATISTIQUE_GLOBAL_H
